---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subathon-timer
  namespace: default
  labels:
    app: subathon-timer
spec:
  replicas: 2
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: subathon-timer
  template:
    metadata:
      labels:
        app: subathon-timer
    spec:
      containers:
      - image: registry.davicoelho.com/subathon-timer/timer:34
        name: subathon-timer
      imagePullSecrets:
      - name: registry-secret
